### ISSUE TITLE
Cannot read property 'stringify' of undefined / default import issue 

### ISSUE THREAD

**Issue by maelle-le-bon** [thomasgazzoni/rxjs-ddp-client#1]
Hi,
I wanted to use your package to connect my non-meteor app with is powered by angular2 to my meteor server.

## Error in debugger:
![Chrom debugger](http://img11.hostingpics.net/pics/579693Sanstitre3.png)
This error append for ejson and underscore library

## Diagnostic
It seem to be a mistake in the typescript compilation
The ejson methods are imported directly on the top of the ejson object. But the typescript transpiler make them import inside the ejson.default object which is wrong (see pictures).
### Transpiled file:
Here the ejson and the underscore library are included:
![code image](http://img11.hostingpics.net/pics/884174Sanstitre3.png)

But you can see that the typescript compiler add the "default" object before the called method:
![Code image](http://img11.hostingpics.net/pics/958906Sanstitre3.png)

Which make spawn errors in the chrome debugger.

## Temporary fix
For the moment I need your library so i remove all the default references in the library which work but i don't find the typescript option which can made a more proper fix.

Cordially

**Comment by maelle-le-bon** [comment]
I am maybe on a fix i try this this afternoon and i made a pull request if it works

**Comment by thomasgazzoni** [comment]
Hi Adam, 
Thanks for opening this issue.
You can try to use the option "allowSyntheticDefaultImports": true, in your project tsconfig.json.
This should tell the typescript compiler to make up a default export and allow to use the shorter syntax for import xxx from xxx for all the libraries.

If it doesn't work I will merge your PR #2

This library come from one of my project so it might still need some fixes to fully decouple it, I will work on it, time allow it.

**Comment by thomasgazzoni** [comment]
Hi Adam, I did some more checks, the code can works only if in your project you set the module to "es2015" together with the allowSyntheticDefaultImports="true" (in the tsconfig.json).
But since this will make problem with node libraries I will merge your PR #2 that will work everywhere.

Thanks for contributing!!
