### ISSUE TITLE
I am unable to setup this library with angular 4. Please help me in this using TypeScript

### ISSUE THREAD

**Issue by mayur-champaneria** [thomasgazzoni/rxjs-ddp-client#3]

**Comment by thomasgazzoni** [comment]
Hi! I just update the library to make the cache system easier to use. 
I also update the README file and add an Angular 4 example.
Let me know the instructions are enough clear now and if you still have any problem.

**Comment by thomasgazzoni** [comment]
Add example folder.
The version [v1.4.0](https://github.com/thomasgazzoni/rxjs-ddp-client/tree/v1.4.0) as been tested in React Native without problem.
