### ISSUE TITLE
Property 'getItem' in type 'MyDDPCacheEngine' is not assignable to the same property in base type 'DDPCacheEngine'.

### ISSUE THREAD

**Issue by ashokj82** [thomasgazzoni/rxjs-ddp-client#4]
import { Observable } from 'rxjs/Observable';
import { DDPCacheEngine } from 'rxjs-ddp-client';
import 'rxjs/add/observable/of';

export class MyDDPCacheEngine implements DDPCacheEngine {

    constructor() {
    }

    getItem(keyName: string) {

        return Observable
            .of(localStorage.getItem(keyName));
    }

    setItem(keyName: string, value: any) {

        return Observable
            .of(localStorage.setItem(keyName, value));
    }

    removeItem(keyName: string) {

        return Observable
            .of(localStorage.removeItem(keyName));
    }
}

Shows error in getItem method

Property 'getItem' in type 'MyDDPCacheEngine' is not assignable to the same property in base type 'DDPCacheEngine'.
  Type '(keyName: string) => Observable<string>' is not assignable to type '(key: string) => Observable<any>'.
    Type 'Observable<string>' is not assignable to type 'Observable<any>'.
      Property 'take' is missing in type 'Observable<string>'.
(method) MyDDPCacheEngine.getItem(keyName: string): Observable<string>

**Comment by thomasgazzoni** [comment]
This issue looks like to be due to the newer version of RxJs where operations are imported separately, I need to have a try, as soon I will get some spare time I will update the dependencies and code then let's see.
Thanks to open this issue.

**Comment by thomasgazzoni** [comment]
Should be fix in the [v1.4.0](https://github.com/thomasgazzoni/rxjs-ddp-client/tree/v1.4.0) version.
If you find any other problem just re-open this issues.
